-- search and replace all CARTMAN0X with X equal to each robot ID, to create table sets in the database.

CREATE TABLE OMNIVEYORS.CARTMAN0X_MOTOR (
	TIMEENTRY TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	STEER1AMP FLOAT(24),
	ROLL1AMP FLOAT(24),
	STEER2AMP FLOAT(24),
	ROLL2AMP FLOAT(24),
	STEER3AMP FLOAT(24),
	ROLL3AMP FLOAT(24),
	STEER4AMP FLOAT(24),
	ROLL4AMP FLOAT(24),
	STEER1AMAX FLOAT(24),
	ROLL1AMAX FLOAT(24),
	STEER2AMAX FLOAT(24),
	ROLL2AMAX FLOAT(24),
	STEER3AMAX FLOAT(24),
	ROLL3AMAX FLOAT(24),
	STEER4AMAX FLOAT(24),
	ROLL4AMAX FLOAT(24)
)
TABLESPACE DATA;
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.TIMEENTRY IS 'Time at which data is measured.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER1AMP IS 'Current through Steer Motor #1 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL1AMP IS 'Current through Roll Motor #1 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER2AMP IS 'Current through Steer Motor #2 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL2AMP IS 'Current through Roll Motor #2 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER3AMP IS 'Current through Steer Motor #3 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL3AMP IS 'Current through Roll Motor #3 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER4AMP IS 'Current through Steer Motor #4 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL4AMP IS 'Current through Roll Motor #4 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER1AMAX IS 'Spike current through Steer Motor #1 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL1AMAX IS 'Spike current through Roll Motor #1 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER2AMAX IS 'Spike current through Steer Motor #2 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL2AMAX IS 'Spike current through Roll Motor #2 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER3AMAX IS 'Spike current through Steer Motor #3 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL3AMAX IS 'Spike current through Roll Motor #3 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.STEER4AMAX IS 'Spike current through Steer Motor #4 (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_MOTOR.ROLL4AMAX IS 'Spike current through Roll Motor #4 (A).';

CREATE TABLE OMNIVEYORS.CARTMAN0X_NAV (
	TIMEENTRY TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	POSX FLOAT(24),
	POSY FLOAT(24),
	ORIENTATION FLOAT(24),
	VELX FLOAT(24),
	VELY FLOAT(24),
	ANGVEL FLOAT(24),
	DESX FLOAT(24),
	DESY FLOAT(24),
	DESORIENT FLOAT(24),
	NAVSTATUS NUMBER
)
TABLESPACE DATA;
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.TIMEENTRY IS 'Time at which data is measured.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.POSX IS 'Position of robot - X (m).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.POSY IS 'Position of robot - Y (m).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.ORIENTATION IS 'Orientation of robot - Z (deg).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.VELX IS 'Linear velocity of robot - X (m/s).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.VELY IS 'Linear velocity of robot - Y (m/s).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.ANGVEL IS 'Angular velocity of robot - Z (deg/s).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.DESX IS 'Desired position of robot - X (m).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.DESY IS 'Desired position of robot - Y (m).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.DESORIENT IS 'Desired orientation of robot - Z (deg).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_NAV.NAVSTATUS IS 'Status of nav stack given the current task.';

CREATE TABLE OMNIVEYORS.CARTMAN0X_PAYLOAD (
	TIMEENTRY TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	STATE NUMBER,
	DPINSTATE NUMBER,
	AIPINSTATE0 NUMBER,
	AIPINSTATE1 NUMBER,
	AIPINSTATE2 NUMBER,
	AIPINSTATE3 NUMBER,
	AIPINSTATE4 NUMBER,
	AIPINSTATE5 NUMBER,
	AOPINSTATE0 NUMBER,
	AOPINSTATE1 NUMBER,
	AOPINSTATE2 NUMBER
)
TABLESPACE DATA;
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.TIMEENTRY IS 'Time at which data is measured.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.STATE IS 'Payload state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.DPINSTATE IS 'Digital GPIO pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE0 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE1 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE2 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE3 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE4 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AIPINSTATE5 IS 'Analog GPI pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AOPINSTATE0 IS 'PWM GPO pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AOPINSTATE1 IS 'PWM GPO pin state.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_PAYLOAD.AOPINSTATE2 IS 'PWM GPO pin state.';

CREATE TABLE OMNIVEYORS.CARTMAN0X_TELEMETRY (
	TIMEENTRY TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	BATTVOLT FLOAT(24),
	BATTAMP FLOAT(24),
	BATTAMAX FLOAT(24),
	IP VARCHAR(16)
)
TABLESPACE DATA;
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_TELEMETRY.TIMEENTRY IS 'Time at which data is measured.';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_TELEMETRY.BATTVOLT IS 'Battery voltage (V).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_TELEMETRY.BATTAMP IS 'Battery drain current estimate (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_TELEMETRY.BATTAMAX IS 'Battery drain current spike estimate (A).';
COMMENT ON COLUMN OMNIVEYORS.CARTMAN0X_TELEMETRY.IP IS 'Robot IP in local network.';
 
